apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo
      tier: backend
  template:
    metadata:
      labels:
        app: yolo
        tier: backend
    spec:
      containers:
        - name: backend
          image: abrahamkinuthia4723/yolo-backend:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/yolodb 
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi