apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: yolo
    tier: database
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: yolo
      tier: database
  template:
    metadata:
      labels:
        app: yolo
        tier: database
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi