apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: yolo
    tier: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None 
  selector:
    app: yolo
    tier: database