
- name: Frontend container setup
  block:
    - name: Stop existing frontend container
      docker_container:
        name: "{{ frontend_container_name }}"
        state: absent
      ignore_errors: yes
      tags: ['frontend']

    - name: Remove existing frontend image
      docker_image:
        name: "{{ frontend_image }}"
        state: absent
        force_absent: yes
      ignore_errors: yes
      tags: ['frontend']

    - name: Build frontend Docker image
      docker_image:
        build:
          path: "{{ app_directory }}/client"
          pull: yes
        name: "{{ frontend_image }}"
        tag: latest
        source: build
        force_source: yes
      tags: ['frontend']

    - name: Run frontend container
      docker_container:
        name: "{{ frontend_container_name }}"
        image: "{{ frontend_image }}:latest"
        state: started
        restart_policy: always
        networks:
          - name: yolo_yolo-network
        ports:
          - "{{ frontend_port }}:3000"
        
        env:
          REACT_APP_API_URL: "http://localhost:{{ backend_port }}"
        links:
          - "{{ backend_container_name }}:backend"
      tags: ['frontend']

    - name: Wait for frontend to be ready
      wait_for:
        port: "{{ frontend_port }}"
        host: "127.0.0.1"
        delay: 20
        timeout: 180
      tags: ['frontend']

  rescue:
    - name: Handle frontend setup errors
      debug:
        msg: "Error setting up frontend: {{ ansible_failed_result.msg }}"
